Create security page and document request identity
restatedev/documentation pull request #431
Opened 2024-07-03 19:10 UTC by jackkleeman

2024-07-03 19:11 UTC, jackkleeman commented on code_snippets/kotlin/src/main/kotlin/develop/ServingIdentity.kt
> +            RestateRequestIdentityVerifier.fromKeys(
@slinkydeveloper is this right?

2024-07-04 15:06 UTC, pcholakov approved these changes
Great addition, thank you for writing this up!

2024-07-04 15:06 UTC, pcholakov commented on docs/develop/java/serving.mdx
> +SDKs are able to validate that incoming requests come from a particular Restate
Simpler 😛

```suggestion
SDKs can validate that incoming requests come from a particular Restate
```

2024-07-04 15:06 UTC, pcholakov commented on docs/develop/ts/serving.mdx
> +SDKs are able to validate that incoming requests come from a particular Restate
```suggestion
SDKs can validate that incoming requests come from a particular Restate
```

2024-07-04 15:06 UTC, pcholakov commented on docs/operate/security.mdx
> +Unrestricted access to the services is dangerous.
Another benefit is to prevent misconfigurations and registering endpoints in the wrong env if operating multiple Restate instances.

2024-07-04 15:06 UTC, pcholakov commented on docs/operate/security.mdx
> +need to be kept secret and even be included in your code when providing to the
This sounds a little odd, maybe an improvement?
```suggestion
need to be kept secret and can be safely included in your code when providing to the
```

2024-07-10 12:19 UTC, slinkydeveloper requested changes

2024-07-10 12:19 UTC, slinkydeveloper commented on code_snippets/kotlin/src/main/kotlin/develop/ServingIdentity.kt
> +            RestateRequestIdentityVerifier.fromKeys(
Yes,

2024-07-10 12:19 UTC, slinkydeveloper commented on docs/develop/java/serving.mdx
> +## Validating request identity
This is missing that you need to pull in the dependency

2024-07-10 12:19 UTC, slinkydeveloper commented on docs/develop/java/serving.mdx
> +## Validating request identity
`dev.restate:sdk-request-identity:VAR::JAVA_SDK_VERSION`

2024-07-10 12:19 UTC, slinkydeveloper commented on code_snippets/kotlin/src/main/kotlin/develop/ServingIdentity.kt
> +            RestateRequestIdentityVerifier.fromKeys(
you're now a kotlin developer :P

2024-07-10 21:00 UTC, merged